part of 'pages.dart';

abstract class Routes {
  static const ONBOARD = '/onboard';
  static const SIGNIN = '/login';
  static const MAIN = '/main';
  static const ADMIN = '/admin';
  static const SPLASH = '/splash';
  static const STAFF_MANAGE = '/staff-manage';
  static const FOOD = '/food';
  static const ADDFOOD = '/add_food';
  static const EDITFOOD = '/edit_food';
  static const ADDTYPEFOOD = '/add_type_food';
  static const LANGUAGE = '/language';
  static const LIST_FOOD = '/list-food';
  // static const CART = '/cart';
  static const MYACCOUNT = '/my_account';
  static const PRINT = '/printer';
  static const ADDPRINTER = '/add_printer';
  static const EDITPRINTER = '/edit_printer';
  static const MANAGE_ORDER = '/manage-order';
  static const ORDER_DETAIL = '/order-detail';
  static const TABLEMANAGE = '/table-manage';
  static const TABLE = '/table';
  static const ADDTABLE = '/add_table';
  static const EDITTABLE = '/edit_table';
  static const VOUCHER = '/voucher';
  static const ADDVOUCHER = '/add_voucher';
  static const EDITVOUCHER = '/edit_voucher';
  static const CHECKINOUT = '/check_in_out';
  static const HISTORY_ORDER = '/history-order';
  static const PRODUCTDETAILS = '/product-detail';
  static const TYPEDETAIL = '/type-detail';
  static const WAITER_CART = '/waiter-cart';
  static const EDIT_ORDER = '/edit-order';
  static const AREA = '/area';
  static const ADDAREA = '/add-area';
  static const EDITAREA = '/edit-area';
  static const CREATE_ORDER_TABLE = '/create-order';
  static const UPSERT_TYPE_FOOD = '/upsert-type-food';
  static const EDITTYPE = '/edit-type';
  static const STAFF_IN_WORKING = '/staff-in-working';
}
